platform: linux/${arch}

clone:
  git:
    image: syncloud/drone-git-${arch}
    depth: 50

pipeline:
  version:
    image: syncloud/build-deps-${arch}
    commands:
      - echo $(date +%y%m%d) > version
      - echo "rocketchat" > name
      
  build:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - NAME=$(cat name)
      - ./build.sh $NAME $VERSION

  test:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - ./integration/test-docker.sh build-$(uname -m)-$DRONE_BRANCH device $(cat package.name) verify.py $(cat name)

  test-ui:
    image: syncloud/build-deps-${arch}
    commands:
      - VERSION=$(cat version)
      - ./integration/test-docker.sh build-$(uname -m)-$DRONE_BRANCH device $(cat package.name) test-ui.py $(cat name)
    shm_size: 1024000000
    when:
      platform: linux/amd64


  upload:
    image: syncloud/build-deps-${arch}
    secrets: [AWS_ACCESS_KEY_ID, AWS_SECRET_ACCESS_KEY]
    commands:
      - VERSION=$(cat version)
      - NAME=$(cat name)
      - ./upload.sh $DRONE_BRANCH $VERSION ${installer}

  ci-artifact:
    image: syncloud/build-deps-${arch}
    secrets: [ARTIFACT_SSH_KEY]
    commands:
      - NAME=$(cat name)
      - ./upload-artifact.sh $NAME integration/log $DRONE_BUILD_NUMBER-${installer}-$(dpkg --print-architecture)
      - ./upload-artifact.sh $NAME integration/screenshot $DRONE_BUILD_NUMBER-${installer}-$(dpkg --print-architecture)
    when:
      status: [ failure, success ] 

services:
  device:
    image: syncloud/systemd-${arch}
    privileged: true
    volumes:
      - /var/run/dbus:/var/run/dbus
 
matrix:
  arch:
    - arm
    - amd64
  installer:
    - snapd